version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - ./secrets/.env
    # environment:
    #   MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #   MARIADB_DATABASE: ${DB_DATABASE}
    #   MARIADB_USER: ${DB_USER}
    #   MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "3307:3306"
  bot:
    build: ./app
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./secrets/.env:/app/secrets/.env:ro
    env_file:
      - ./secrets/.env
  
volumes:
  db_data: